# Generated by Django 5.1.3 on 2024-12-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_alter_task_options_remove_task_is_urgent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
